import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import {
  ICategory,
  ICategoryFields,
  IPostFields,
  IPost,
} from '../../@types/generated/contentful';
import { GetStaticPaths } from 'next';
import client from '../../contentful/contenful';
import { sortedPosts } from '../../utils/posts';
import PostTile from '../../components/PostTile';
import Link from 'next/link';
import { UserIcon } from '@heroicons/react/outline';

type PostPropTypes = {
  posts: IPost[];
  category: ICategory;
  categories: ICategory[];
};

const Category: NextPage<PostPropTypes> = ({ category, posts, categories }) => {
  const relevantPosts = posts.filter((post) =>
    post.fields.categories.some(
      (cat) =>
        cat.fields.name.toLocaleLowerCase() ===
        category.fields.name.toLocaleLowerCase()
    )
  );

  return (
    <div>
      <Head>
        <title>{category.fields.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center bg-slate-300 text-xl uppercase py-1 font-heading">
        nac development
      </div>
      <div className="sticky top-0 bg-white z-10 shadow border-b mb-6">
        <div className="m-auto max-w-2xl py-2 flex h-12">
          <nav className="flex flex-1 self-stretch items-center">
            {categories.map((cat) => (
              <Link
                key={cat.fields.name}
                href={`/categories/${cat.fields.name?.toLowerCase()}`}
              >
                <a
                  className={`flex mx-2 cursor-pointer hover:text-gray-500 ${
                    cat.fields.name.toLowerCase() ===
                    category.fields.name.toLowerCase()
                      ? 'text-gray-700'
                      : 'text-gray-400'
                  }`}
                >
                  {cat.fields.name}
                </a>
              </Link>
            ))}
          </nav>
          <div className="flex text-red-500 items-center">
            login
            <UserIcon className="h-5 w-5" />
          </div>
        </div>
      </div>
      <main className="flex justify-center">
        <div className="flex max-w-2xl flex-col">
          {sortedPosts(relevantPosts).map((post) => (
            <PostTile key={post.sys.id} post={post} />
          ))}
        </div>
      </main>
    </div>
  );
};

export default Category;

export const getStaticPaths: GetStaticPaths = async () => {
  const { items } = await client.getEntries<ICategoryFields>({
    content_type: 'category',
    select: 'fields.name',
  });

  const paths = items.map((item) => {
    return {
      params: {
        category: item.fields.name.toLowerCase(),
      },
    };
  });

  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const categoryEntries = await client.getEntries<ICategoryFields>({
    content_type: 'category',
  });

  const postEntries = await client.getEntries<IPostFields>({
    content_type: 'post',
  });

  return {
    props: {
      posts: postEntries.items,
      category: categoryEntries.items.filter(
        (item) => item.fields.name.toLowerCase() === params!.category
      )[0],
      categories: categoryEntries.items,
    },
    revalidate: 1,
  };
};
