import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import client from '../contentful/contenful';
import { ICategory, ICategoryFields } from '../@types/generated/contentful';

type PropsType = {
  categories: ICategory[];
};

const FourOhFour: NextPage<PropsType> = ({ categories }) => {
  return (
    <>
      <Head>
        <title>nac blog: 404</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex justify-center">
        <div className="flex">404 | Oups...</div>
      </div>
    </>
  );
};

export default FourOhFour;

export const getStaticProps: GetStaticProps = async () => {
  const categoryEntries = await client.getEntries<ICategoryFields>({
    content_type: 'category',
  });

  return {
    props: {
      categories: categoryEntries.items,
    },
    revalidate: 1,
  };
};
