import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import { getPageData } from '../hygraph/Page';
import { CategoriesItem } from '../hygraph/Panel';

type PropsType = {
  categories: CategoriesItem[];
};

const FourOhFour: NextPage<PropsType> = () => {
  return (
    <>
      <Head>
        <title>nac blog: 404</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex justify-center">
        <div className="flex">404 | Oups...</div>
      </div>
    </>
  );
};

export default FourOhFour;

export const getStaticProps: GetStaticProps = async () => {
  const { panel, header } = await getPageData('category');

  return {
    props: {
      categories: header.navbar.categories,
      panel: panel,
    },
    revalidate: 1,
  };
};
