import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import { getData, getNavbar } from '../hygraph/getData';
import { getPanelData } from '../hygraph/Panel';
import { IPostData } from '../@types/posts';
import PostsList from '../components/PostsList';
import { EVERYTHING } from '../utils/categories';
import { getPageData } from '../hygraph/Page';

type HomePropsType = {
  posts: IPostData[];
};

const Home: NextPage<HomePropsType> = ({ posts }) => {
  return (
    <>
      <Head>
        <title>nac blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col gap-y-4">
        <PostsList posts={posts} />
      </div>
    </>
  );
};
export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const { posts } = await getData();
  const { categories } = await getNavbar('Main');
  const page = await getPageData('index');

  return {
    props: {
      posts,
      categories,
      category: EVERYTHING,
      panel: page.panel,
    },
    revalidate: 1,
  };
};
