import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import {
  IPost,
  IPostFields,
  ICategory,
  ICategoryFields,
} from '../@types/generated/contentful';
import client from '../contentful/contenful';
import PostTile from '../components/PostTile';
import { useState } from 'react';

type HomePropsType = {
  posts: IPost[];
  categories: ICategory[];
};

const sortedPosts = (posts: IPost[]) => {
  return posts.sort((a, b) => {
    return (
      new Date(b.sys.createdAt).getTime() - new Date(a.sys.createdAt).getTime()
    );
  });
};

const Home: NextPage<HomePropsType> = ({ posts, categories }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center bg-slate-300 text-xl uppercase py-1 font-heading">
        nac development
      </div>
      <nav className="flex py-4 mb-6 bg-white justify-center items-center sticky top-0 border-b z-10">
        <ul className="flex">
          {categories.map((category) => (
            <li
              className="flex mx-2 cursor-pointer text-gray-700"
              key={category.fields.name}
            >
              {category.fields.name}
            </li>
          ))}
        </ul>
      </nav>
      <main className="flex justify-center">
        <div className="flex max-w-2xl flex-col">
          {sortedPosts(posts).map((post) => (
            <PostTile key={post.sys.id} post={post} />
          ))}
        </div>
      </main>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const postEntries = await client.getEntries<IPostFields>({
    content_type: 'post',
  });

  const categoryEntries = await client.getEntries<ICategoryFields>({
    content_type: 'category',
  });

  return {
    props: {
      posts: postEntries.items,
      categories: categoryEntries.items,
    },
    revalidate: 1,
  };
};
